
/*
Code automatically generated by asn1scc tool
*/
#include <string.h>
#include "sample1.h"

MyTestPDU testPDU = "George Mamais       ";


void MyTestPDU_Initialize(MyTestPDU pVal)
{

    memset(pVal, 0x0, 21);
}

flag CheckString1(const char* str);

flag MyTestPDU_IsConstraintValid(MyTestPDU pVal, int* pErrCode)
{
    if ( !((strlen(pVal) == 20) && CheckString1(pVal)) ) {
        *pErrCode = ERR_MyTestPDU;
        return FALSE;
    }
    (void)pVal; /*Dummy statement, just to hide potential warning*/
    (void)pErrCode; /*Dummy statement, just to hide potential warning*/
    return TRUE;
}

flag CheckString1(const char* str)
{
    size_t i;
    size_t n = strlen(str);
    for(i=0;i<n;i++)
    {
        if (!(((str[i]>='A') && (str[i]<='Z')) || ((str[i]>='a') && (str[i]<='z')) || strchr(" ", str[i])))
            return FALSE;
    }
    return TRUE;
}
flag MyTestPDU_Encode(MyTestPDU pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    int i1 = 0;

    if (bCheckConstraints && !MyTestPDU_IsConstraintValid(pVal, pErrCode))
        return FALSE;
    /* No need to encode length (it is fixed size (20)*/
    for(i1=0;i1<strlen(pVal);i1++)
    {
        static byte allowedCharSet[] = {0x20,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,0x4A,0x4B,0x4C,0x4D,0x4E,
                                    0x4F,0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5A,0x61,0x62,0x63,
                                    0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,0x72,
                                    0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
        int charIndex = GetCharIndex(pVal[i1], allowedCharSet,53);
        BitStream_EncodeConstraintWholeNumber(pBitStrm, charIndex, 0, 52);
    }
    return TRUE;
}

flag MyTestPDU_Decode(MyTestPDU pVal, BitStream* pBitStrm, int* pErrCode)
{
    int i1 = 0;

    memset(pVal, 0x0, 21);
    for(i1=0;i1<20;i1++)
    {
        static byte allowedCharSet[] = {0x20,0x41,0x42,0x43,0x44,0x45,0x46,0x47,0x48,0x49,0x4A,0x4B,0x4C,0x4D,0x4E,
                                    0x4F,0x50,0x51,0x52,0x53,0x54,0x55,0x56,0x57,0x58,0x59,0x5A,0x61,0x62,0x63,
                                    0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F,0x70,0x71,0x72,
                                    0x73,0x74,0x75,0x76,0x77,0x78,0x79,0x7A};
        asn1SccSint charIndex = 0;
        if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &charIndex, 0, 52)) {
            *pErrCode = ERR_INSUFFICIENT_DATA;
            return FALSE;
        }
        pVal[i1] = allowedCharSet[charIndex];
    }
    return TRUE;
}

