
/*
Code automatically generated by asn1cc tool
*/
#include <string.h>
#include "sample1.h"

void MyTestPDU_Initialize(MyTestPDU* pVal)
{

    int i1 = 0;

    pVal->nCount = 0;
    for(i1=0;i1<20;i1++)
    {
        pVal->arr[i1].int1 = 0;
        pVal->arr[i1].int2 = 0;
        pVal->arr[i1].enm = arr_enm_one;
        pVal->arr[i1].buf.nCount = 0;
        memset(pVal->arr[i1].buf.arr,0x0,10);
        pVal->arr[i1].gg.int1 = 0;
        pVal->arr[i1].gg.int2 = 0;
        pVal->arr[i1].gg.enm = gg_enm_one;
        pVal->arr[i1].gg.buf.nCount = 0;
        memset(pVal->arr[i1].gg.buf.arr,0x0,10);
    }
}


flag MyTestPDU_IsConstraintValid(MyTestPDU* pVal, int* pErrCode)
{
    int i1 = 0;

    if ( !(((pVal->nCount>=0) && (pVal->nCount<=20))) ) {
        *pErrCode = ERR_MyTestPDU;
        return FALSE;
    }

    for(i1=0;i1<pVal->nCount;i1++)
    {
        if ( !(((pVal->arr[i1].int1>=0) && (pVal->arr[i1].int1<=15))) ) {
            *pErrCode = ERR_MyTestPDU_elem_int1;
            return FALSE;
        }

        if ( !(((pVal->arr[i1].int2>=0) && (pVal->arr[i1].int2<=65535))) ) {
            *pErrCode = ERR_MyTestPDU_elem_int2;
            return FALSE;
        }


        if ( !((pVal->arr[i1].buf.nCount == 10)) ) {
            *pErrCode = ERR_MyTestPDU_elem_buf;
            return FALSE;
        }

        if ( pVal->arr[i1].exist.gg ) {
            if ( !(((pVal->arr[i1].gg.int1>=0) && (pVal->arr[i1].gg.int1<=15))) ) {
                *pErrCode = ERR_MyTestPDU_elem_gg_int1;
                return FALSE;
            }

            if ( !(((pVal->arr[i1].gg.int2>=0) && (pVal->arr[i1].gg.int2<=65535))) ) {
                *pErrCode = ERR_MyTestPDU_elem_gg_int2;
                return FALSE;
            }


            if ( !((pVal->arr[i1].gg.buf.nCount == 10)) ) {
                *pErrCode = ERR_MyTestPDU_elem_gg_buf;
                return FALSE;
            }

        }

    }
    return TRUE;
}

flag MyTestPDU_Encode(MyTestPDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    int i1 = 0;
    int i2 = 0;

    if (bCheckConstraints && !MyTestPDU_IsConstraintValid(pVal, pErrCode))
        return FALSE;
    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 20);
    for(i1=0;i1<pVal->nCount;i1++)
    {
        /*Encode childlen : (SEQUENCE)*/
        /* Encode Bit Mask for optional and default fields*/
        BitStream_AppendBit(pBitStrm, pVal->arr[i1].exist.gg);

        /*Encode int1 (INTEGER)*/
        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->arr[i1].int1, 0, 15);

        /*Encode int2 (INTEGER)*/
        BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->arr[i1].int2, 0, 65535);

        /*Encode enm (ENUMERATED)*/
        switch(pVal->arr[i1].enm)
        {
        case arr_enm_one:
            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 4);
            break;
        case arr_enm_two:
            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 4);
            break;
        case arr_enm_three:
            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 4);
            break;
        case arr_enm_four:
            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 4);
            break;
        case arr_enm_thousand:
            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 4);
            break;
        }

        /*Encode buf (OCTET STRING)*/
        /* No need to encode length (it is fixed size (10)*/
        for(i2=0;i2<pVal->arr[i1].buf.nCount;i2++)
        {
            BitStream_AppendByte0(pBitStrm, pVal->arr[i1].buf.arr[i2]);
        }

        /*Encode gg (SEQUENCE)*/
        if ( pVal->arr[i1].exist.gg ) {

            /*Encode int1 (INTEGER)*/
            BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->arr[i1].gg.int1, 0, 15);

            /*Encode int2 (INTEGER)*/
            BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->arr[i1].gg.int2, 0, 65535);

            /*Encode enm (ENUMERATED)*/
            switch(pVal->arr[i1].gg.enm)
            {
            case gg_enm_one:
                BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 4);
                break;
            case gg_enm_two:
                BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 4);
                break;
            case gg_enm_three:
                BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 4);
                break;
            case gg_enm_four:
                BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 4);
                break;
            case gg_enm_thousand:
                BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 4);
                break;
            }

            /*Encode buf (OCTET STRING)*/
            /* No need to encode length (it is fixed size (10)*/
            for(i2=0;i2<pVal->arr[i1].gg.buf.nCount;i2++)
            {
                BitStream_AppendByte0(pBitStrm, pVal->arr[i1].gg.buf.arr[i2]);
            }

        }

    }
    return TRUE;
}

flag MyTestPDU_Decode(MyTestPDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    asn1SccSint nCount = 0;
    int i1 = 0;
    byte bitMask[1];
    asn1SccSint enumIndex = 0;
    int i2 = 0;

    if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 20)) {
        *pErrCode = ERR_INSUFFICIENT_DATA;
        return FALSE;
    }
    pVal->nCount = (long)nCount;
    for(i1=0;i1<pVal->nCount;i1++)
    {
        /*Decode childlen : (SEQUENCE)*/
        if (!BitStream_ReadBits(pBitStrm, bitMask, 1)) {
            *pErrCode = ERR_INSUFFICIENT_DATA;
            return FALSE;
        }
        /*Decode int1 (INTEGER)*/
        if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &pVal->arr[i1].int1, 0, 15)) {
            *pErrCode = ERR_INSUFFICIENT_DATA;
            return FALSE;
        }
        /*Decode int2 (INTEGER)*/
        if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &pVal->arr[i1].int2, 0, 65535)) {
            *pErrCode = ERR_INSUFFICIENT_DATA;
            return FALSE;
        }
        /*Decode enm (ENUMERATED)*/
        if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 4)) {
            *pErrCode = ERR_INSUFFICIENT_DATA;
            return FALSE;
        }
        switch(enumIndex)
        {
        case 0:
            pVal->arr[i1].enm = arr_enm_one;
            break;
        case 1:
            pVal->arr[i1].enm = arr_enm_two;
            break;
        case 2:
            pVal->arr[i1].enm = arr_enm_three;
            break;
        case 3:
            pVal->arr[i1].enm = arr_enm_four;
            break;
        case 4:
            pVal->arr[i1].enm = arr_enm_thousand;
            break;
        }
        /*Decode buf (OCTET STRING)*/
        pVal->arr[i1].buf.nCount = 10;
        for(i2=0;i2<pVal->arr[i1].buf.nCount;i2++)
        {
            if ( !BitStream_ReadByte(pBitStrm, &pVal->arr[i1].buf.arr[i2]) ) {
                *pErrCode = ERR_INSUFFICIENT_DATA;
                return FALSE;
            }
        }
        /*Decode gg (SEQUENCE)*/
        pVal->arr[i1].exist.gg = 0;
        if ((bitMask[0] & 0x80) != 0 ) {
            pVal->arr[i1].exist.gg = 1;
                        /*Decode int1 (INTEGER)*/
            if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &pVal->arr[i1].gg.int1, 0, 15)) {
                *pErrCode = ERR_INSUFFICIENT_DATA;
                return FALSE;
            }
            /*Decode int2 (INTEGER)*/
            if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &pVal->arr[i1].gg.int2, 0, 65535)) {
                *pErrCode = ERR_INSUFFICIENT_DATA;
                return FALSE;
            }
            /*Decode enm (ENUMERATED)*/
            if (!BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 4)) {
                *pErrCode = ERR_INSUFFICIENT_DATA;
                return FALSE;
            }
            switch(enumIndex)
            {
            case 0:
                pVal->arr[i1].gg.enm = gg_enm_one;
                break;
            case 1:
                pVal->arr[i1].gg.enm = gg_enm_two;
                break;
            case 2:
                pVal->arr[i1].gg.enm = gg_enm_three;
                break;
            case 3:
                pVal->arr[i1].gg.enm = gg_enm_four;
                break;
            case 4:
                pVal->arr[i1].gg.enm = gg_enm_thousand;
                break;
            }
            /*Decode buf (OCTET STRING)*/
            pVal->arr[i1].gg.buf.nCount = 10;
            for(i2=0;i2<pVal->arr[i1].gg.buf.nCount;i2++)
            {
                if ( !BitStream_ReadByte(pBitStrm, &pVal->arr[i1].gg.buf.arr[i2]) ) {
                    *pErrCode = ERR_INSUFFICIENT_DATA;
                    return FALSE;
                }
            }
        }
    }
    return TRUE;
}


void MyInt_Initialize(MyInt* pVal)
{

    *pVal = 0;
}


flag MyInt_IsConstraintValid(MyInt* pVal, int* pErrCode)
{
    return TRUE;
}

flag MyInt_Encode(MyInt* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    if (bCheckConstraints && !MyInt_IsConstraintValid(pVal, pErrCode))
        return FALSE;
    BitStream_EncodeUnConstraintWholeNumber(pBitStrm, *pVal);
    return TRUE;
}

flag MyInt_Decode(MyInt* pVal, BitStream* pBitStrm, int* pErrCode)
{
    if (!BitStream_DecodeUnConstraintWholeNumber(pBitStrm, pVal)) {
        *pErrCode = ERR_INSUFFICIENT_DATA;
        return FALSE;
    }
    return TRUE;
}


MyTestPDU testPDU = {
    10,
    {
        {
            .int1 = 10,
            .int2 = 200,
            .enm = arr_enm_one,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0xFF,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0xFF,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0xFF,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        },
        {
            .int1 = 15,
            .int2 = 3200,
            .enm = arr_enm_two,
            .buf = {
                10,
                {
                    0x00,
                    0x11,
                    0x22,
                    0x33,
                    0x44,
                    0x55,
                    0x66,
                    0x77,
                    0x88,
                    0x99
                }
            },
            .gg = {
                .int1 = 10,
                .int2 = 200,
                .enm = gg_enm_one,
                .buf = {
                    10,
                    {
                        0x00,
                        0x11,
                        0x22,
                        0x33,
                        0x44,
                        0x55,
                        0x66,
                        0x77,
                        0x88,
                        0x99
                    }
                }
            },
            .exist = {
                .gg = 1
            }
        }
    }
};
