//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asn1scc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("asn1scc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifndef _INC_PER_UTIL_H
        ///#define _INC_PER_UTIL_H
        ///
        ///
        ///#ifdef  __cplusplus
        ///extern &quot;C&quot; {
        ///#endif
        ///
        ///#ifndef NULL
        ///#define NULL	0
        ///#endif
        ///
        ///#define TRUE	1
        ///#define FALSE	0
        ///
        ///
        ///
        ///#ifndef WORD_SIZE
        ///#define WORD_SIZE	8
        ///#endif
        ///
        ///typedef long asn1SccSint32;
        ///typedef unsigned long asn1SccUint32;
        ///
        ///typedef unsigned char byte;
        ///
        ///
        ///#if WORD_SIZE==8
        ///typedef long long asn1SccSint64;
        ///typedef unsigned long long asn1SccUint64;
        ///typedef asn1SccUint64 asn1SccUint;
        ///typedef asn1SccSint64 asn1SccSint;
        ///#else
        ///typedef  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string asn1crt {
            get {
                return ResourceManager.GetString("asn1crt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;string.h&gt;
        ///#include &lt;assert.h&gt;
        ///#include &lt;math.h&gt;
        ///#include &lt;float.h&gt;
        ///
        ///#include &quot;asn1crt.h&quot;
        ///
        ///
        ///byte masks[] = {0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01};
        ///byte masksb[] = {0x0, 0x1, 0x3, 0x7, 0xF, 0x1F, 0x3F, 0x7F, 0xFF};
        ///
        ///asn1SccUint32 masks2[] = {0x0, 0xFF, 
        ///						0xFF00, 
        ///						0xFF0000, 
        ///						0xFF000000
        ///					};
        ///#if WORD_SIZE==8
        ///asn1SccUint64 masks2b[] = {0x0, 0xFF, 
        ///						0xFF00, 
        ///						0xFF0000, 
        ///						0xFF000000, 
        ///						0xFF00000000ULL, 
        ///						0xFF0000000000ULL, 
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string asn1crt1 {
            get {
                return ResourceManager.GetString("asn1crt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;assert.h&gt;
        ///#include &lt;float.h&gt;
        ///#include &lt;math.h&gt;
        ///#include &quot;asn1crt.h&quot;
        ///
        ///#if WORD_SIZE==8
        ///#define MAX_MANTISSA 4503599627370496
        ///#else
        ///#define MAX_MANTISSA 2147483648
        ///#endif
        ///
        ///#if WORD_SIZE==8
        ///#define MANTISSA_FACTOR 4503599627370496.0
        ///#define EXPONENET_FACTOR 52
        ///#else
        ///#define MANTISSA_FACTOR 4294967296.0
        ///#define EXPONENET_FACTOR 32
        ///
        ///#endif
        ///
        ///
        ///
        ///#ifndef FREXP_UNSUPPORTED
        ///
        ///void CalculateMantissaAndExponent(double d, int* exp, asn1SccUint* mantissa)
        ///{
        ///	double dman = frexp(d,exp);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string real {
            get {
                return ResourceManager.GetString("real", resourceCulture);
            }
        }
    }
}
