
/*
Code automatically generated by asn1cc tool
*/
#include <string.h>
#include <assert.h>
#include "sample1.h"

void MyTestPDU_Initialize(MyTestPDU* pVal)
{
    *pVal = 0;
}


flag MyTestPDU_IsConstraintValid(MyTestPDU* pVal, int* pErrCode)
{
    flag ret;
    ret =(((*pVal>=1) && (*pVal<=256))||(*pVal == 400));
    if (!ret) {
        *pErrCode = ERR_MyTestPDU_CONSTRAINT_FAILED;
        return FALSE;
    }
    return TRUE;
}

flag MyTestPDU_Encode(MyTestPDU* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    if (bCheckConstraints && !MyTestPDU_IsConstraintValid(pVal, pErrCode))
        return FALSE;
    if ((*pVal>=1) && (*pVal<=256)) {
        BitStream_AppendBitZero(pBitStrm); /* value within root range, so ext bit is zero*/
        BitStream_EncodeConstraintWholeNumber(pBitStrm, *pVal, 1, 256);
    } else {
        /* value is not within root range, so ext bit is one and value is encoded as uncostraint*/
        BitStream_AppendBitOne(pBitStrm);
        BitStream_EncodeUnConstraintWholeNumber(pBitStrm, *pVal);
    }
    return TRUE;
}

flag MyTestPDU_Decode(MyTestPDU* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, 1, 256);
    if (!ret)
        return FALSE;
    return TRUE;
}


MyTestPDU testPDU = -256;
