#ifndef _INC_SAMPLE1_H
#define _INC_SAMPLE1_H
/*
Code automatically generated by asn1cc tool
*/

#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif

/* This a test */
typedef struct {
    /* int1	INTEGER(0..15), */
    struct {
        long nCount;
        struct {
            long nCount;
            sint  arr[200000];
        } arr[100000];
    } doubleArr;
} MyTestPDU;

#define MyTestPDU_REQUIRED_BYTES_FOR_ENCODING		20000600004

#define ERR_MyTestPDU_doubleArr		1000 /* (SIZE (1..100000)) */
#define ERR_MyTestPDU_doubleArr_elem		1001 /* (SIZE (1..200000)) */
#define ERR_MyTestPDU_doubleArr_elem_elem		1002 /* (0..255) */

void MyTestPDU_Initialize(MyTestPDU* pVal);
flag MyTestPDU_IsConstraintValid(MyTestPDU* val, int* pErrCode);
flag MyTestPDU_Encode(MyTestPDU* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag MyTestPDU_Decode(MyTestPDU* val, BitStream* pBitStrm, int* pErrCode);


#ifdef  __cplusplus
}
#endif

#endif
