MY-MODULE DEFINITIONS AUTOMATIC TAGS::= BEGIN
	
	
	ID ::= NumericString ( FROM(ALL EXCEPT " ") )	


	MITSOS ::= SEQUENCE {
		a  ID	DEFAULT "12 345",	--error
		b  ID	DEFAULT "67890"
	}
	
	
END
