--FRange exception support
--EMyMod&nbsp;&nbsp;DEFINITIONS ::=
--EBEGIN
--E&nbsp;&nbsp;Int ::= INTEGER (MIN..5)&nbsp;&nbsp;
--EEND


MyMod	DEFINITIONS ::=
BEGIN
	
	Int ::= INTEGER (MIN..5)	

END
